dist: trusty
sudo: false
language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4
      - cmake

script:
  - CXX=/usr/bin/g++-4 CC=/usr/bin/gcc-4 cmake -D .
  - cmake --build . -- -j2 
  - ctest -j2



